import Foundation

final class MarkdownTemplateService {

    static let shared = MarkdownTemplateService()
    private init() {}

    func designBrief(project: FactoryProject, analysis: ArtworkAnalysis) -> String {
        let dateStr = DateFormatter.localizedString(from: project.createdAt, dateStyle: .long, timeStyle: .none)
        let colors = analysis.dominantColors.map { "  - \($0.hex)  (R:\($0.r) G:\($0.g) B:\($0.b))" }.joined(separator: "\n")
        return """
        # DESIGN BRIEF
        **Project Code:** \(project.projectCode)
        **Project Name:** \(project.displayName)
        **Collection:** \(project.displayCollectionName)
        **Date:** \(dateStr)
        **Factory:** \(project.factoryName.isEmpty ? "Not specified" : project.displayFactoryName)

        ---

        ## Product Information
        - **Product Type:** \(project.productType.rawValue)
        - **Material:** \(project.material.rawValue)
        - **Print Method:** \(project.printMethod.rawValue)

        ## Visual Description
        *[Describe the visual concept, motifs, and mood of the artwork here.]*

        - **Motifs:** To be described based on artwork
        - **Color Mood:** Extracted palette below
        - **Artwork Style:** Bitmap / Raster — requires vectorization

        ## Extracted Color Palette
        \(colors.isEmpty ? "  - No colors extracted" : colors)

        > ⚠️ Factory must confirm final colors using physical sample or Pantone/CMYK references.

        ## Notes
        \(project.notes.isEmpty ? "No additional notes." : project.notes)

        ---
        *Generated by PrintFactoryKit — For factory review only.*
        """
    }

    func colorPalette(project: FactoryProject, analysis: ArtworkAnalysis) -> String {
        let rows = analysis.dominantColors.enumerated().map { i, c in
            "| \(i + 1) | \(c.hex) | R:\(c.r) G:\(c.g) B:\(c.b) | Pantone TBD | CMYK TBD |"
        }.joined(separator: "\n")
        return """
        # COLOR PALETTE
        **Project:** \(project.projectCode) — \(project.displayName)

        | # | HEX | RGB | Pantone (required) | CMYK (required) |
        |---|-----|-----|--------------------|-----------------|
        \(rows.isEmpty ? "| — | No colors extracted | — | — | — |" : rows)

        ---

        ## Important Notice
        > These colors are algorithmically extracted from the raster source image.
        > They are approximate values for reference only.
        >
        > **Factory must confirm all final colors using:**
        > - Physical print sample
        > - Pantone Textile/Coated swatch confirmation
        > - CMYK profile matching appropriate for the chosen print method
        >
        > Color variation of ±5–10% is expected between digital preview and physical print.

        ---
        *Generated by PrintFactoryKit — Color values are approximate.*
        """
    }

    func productionNotes(project: FactoryProject, analysis: ArtworkAnalysis) -> String {
        let resNote = analysis.dpiEstimateNote
        let materialNotes = materialSpecificNotes(project: project)
        return """
        # PRODUCTION NOTES
        **Project:** \(project.projectCode) — \(project.displayName)

        ---

        ## Source Artwork Status
        - **Format:** \(analysis.fileFormat)
        - **Dimensions:** \(analysis.pixelWidth) × \(analysis.pixelHeight) px
        - **File Size:** \(analysis.fileSizeFormatted)
        - **Resolution Note:** \(resNote)
        - **Source Type:** Raster/Bitmap (not vector)

        ## Material & Process Notes
        \(materialNotes)

        ## Required Preparation Before Factory Production

        ### 1. Vectorization
        - [ ] Convert artwork to vector format (AI, EPS, or SVG)
        - [ ] Minimum recommended: 300 DPI equivalent at print dimensions
        - [ ] Use professional software: Adobe Illustrator, Affinity Designer, or similar
        - [ ] **Status: NEEDS PROFESSIONAL PREPARATION**

        ### 2. Seamless Repeat Tile
        - [ ] Create seamless repeat tile appropriate for product dimensions
        - [ ] Variants: seamless, sparse, dense, mini motif
        - [ ] **Status: NOT PROVIDED — NEEDS PREPARATION**

        ### 3. Print Scale
        - [ ] Define intended print scale relative to product dimensions
        - [ ] Confirm with factory minimum repeat size requirements
        - [ ] Product: \(project.productType.rawValue)

        ### 4. Color Separation
        - [ ] Confirm print method: \(project.printMethod.rawValue)
        - [ ] For Digital Textile Print: ICC profile required
        - [ ] For Screen Print: Color separation by channel required
        - [ ] For Sublimation: Confirm substrate compatibility with \(project.material.rawValue)

        ## Sample Approval Requirement
        > ⚠️ Physical factory sample MUST be approved before mass production.
        > Do NOT proceed to production without signed sample approval.

        ---
        *Generated by PrintFactoryKit.*
        """
    }

    private func materialSpecificNotes(project: FactoryProject) -> String {
        switch project.material {
        case .cetimColado:
            return """
            - **Material:** Cetim + Lona (impressão no cetim, colado na lona)
            - **Process:** Arte é impressa digitalmente no cetim; o cetim impresso é
              então colado sobre a lona estrutural da bolsa.
            - **Confirm with factory:**
              - [ ] Tipo de cola utilizado (PU, hot-melt, etc.)
              - [ ] Espessura do cetim e da lona
              - [ ] Resistência da colagem à água e ao uso
              - [ ] Temperatura e pressão do processo de colagem
              - [ ] Área de sangramento (bleed) necessária nas bordas
              - [ ] Comportamento das cores do cetim após colagem (possível shift)
            - **⚠️ Warning:** Impressão em cetim pode apresentar variação de cor
              diferente do monitor — amostra física obrigatória.
            """
        case .polyesterElastano:
            return """
            - **Material:** Poliéster com Elastano
            - **Process:** Impressão sublimática é o método recomendado para este material.
              O elastano permite elasticidade — ideal para cangas e peças de praia.
            - **Confirm with factory:**
              - [ ] Percentual de elastano na composição (ex: 92% PES / 8% EA)
              - [ ] Gramatura do tecido (g/m²)
              - [ ] Compatibilidade com sublimação (poliéster mínimo ~85%)
              - [ ] Encolhimento após lavagem
              - [ ] Comportamento das bordas (costura, bainha ou corte a laser)
              - [ ] Padrão de cor após sublimação — realizar teste de cor antes do bulk
            - **⚠️ Warning:** Elastano pode reduzir a intensidade das cores na sublimação.
              Ajuste de cor na arte pode ser necessário — confirmar com fábrica.
            """
        case .canvas12oz:
            return """
            - **Material:** Canvas 12 oz
            - **Process:** Impressão digital têxtil ou serigrafia conforme método selecionado.
            - **Confirm with factory:**
              - [ ] Acabamento da lona (cru, branqueado, tingido)
              - [ ] Compatibilidade com o método de impressão selecionado
              - [ ] Resistência à lavagem após impressão
            """
        case .polyester:
            return """
            - **Material:** Poliéster
            - **Process:** Sublimação ou impressão digital têxtil conforme método.
            - **Confirm with factory:**
              - [ ] Gramatura do tecido
              - [ ] Compatibilidade com método de impressão selecionado
            """
        case .cotton:
            return """
            - **Material:** Algodão (Cotton)
            - **Note:** Algodão não é compatível com sublimação. Use impressão digital
              têxtil (DTG/DTF) ou serigrafia.
            - **Confirm with factory:**
              - [ ] Fio e gramatura
              - [ ] Pré-tratamento necessário para impressão
            """
        case .other:
            return "- **Material:** Outro — confirmar especificações diretamente com a fábrica."
        }
    }

    private func techPackMaterialDetail(project: FactoryProject) -> String {
        switch project.material {
        case .cetimColado:
            return """
            - **Outer layer:** Cetim impresso digitalmente
            - **Base layer:** Lona (canvas estrutural)
            - **Bond process:** Colagem — tipo de cola a confirmar com fábrica
            - **⚠️ Process note:** Confirmar resistência da colagem, bleed nas bordas e shift de cor
            """
        case .polyesterElastano:
            return """
            - **Composition:** Poliéster + Elastano (% a confirmar com fábrica)
            - **Recommended print:** Sublimação
            - **⚠️ Process note:** Confirmar % mínimo de PES para sublimação e comportamento do elastano
            """
        case .canvas12oz:
            return "- **Weight:** 12 oz / 340 g/m² approximately"
        case .polyester, .cotton, .other:
            return ""
        }
    }

    func techPack(project: FactoryProject, analysis: ArtworkAnalysis) -> String {
        let s = project.specs
        let hasDims = s.widthCM > 0 || s.heightCM > 0
        let hasPrint = s.printAreaWidthCM > 0 || s.printAreaHeightCM > 0
        let hasZipper = !s.zipperColor.isEmpty || s.zipperLengthCM > 0
        let hasStrap = !s.strapMaterial.isEmpty || s.strapWidthCM > 0

        let dimLine     = hasDims  ? s.dimensionSummary : "⚠️ Not specified — confirm with factory"
        let printLine   = hasPrint ? s.printAreaSummary + " @ \(s.targetDPI) DPI" : "⚠️ Not specified — confirm with factory"
        let zipperLine  = hasZipper
            ? [s.zipperColor, s.zipperType, s.zipperLengthCM > 0 ? "\(s.zipperLengthCM) cm" : ""].filter { !$0.isEmpty }.joined(separator: ", ")
            : "⚠️ Not specified"
        let strapLine   = hasStrap
            ? [s.strapMaterial, s.strapWidthCM > 0 ? "W:\(s.strapWidthCM) cm" : "", s.strapLengthCM > 0 ? "L:\(s.strapLengthCM) cm" : ""].filter { !$0.isEmpty }.joined(separator: ", ")
            : "⚠️ Not specified"
        let liningLine  = s.liningColor.isEmpty ? "⚠️ Not specified" : "\(s.liningColor)\(s.liningMaterial.isEmpty ? "" : " — \(s.liningMaterial)")"
        let seamLine    = s.seam.isEmpty ? "1 cm overlock (default — confirm)" : s.seam
        let qtyLine     = s.targetQuantity > 0 ? "\(s.targetQuantity) units" : "⚠️ Not defined — confirm MOQ with factory"

        let printPx = hasPrint ? " (\(s.printPixelWidth) × \(s.printPixelHeight) px at \(s.targetDPI) DPI)" : ""

        return """
        # PRODUCT TECH PACK
        **Project:** \(project.projectCode) — \(project.displayName)
        **Collection:** \(project.displayCollectionName)
        **Product:** \(project.productType.rawValue)
        **Factory:** \(project.factoryName.isEmpty ? "Not specified" : project.displayFactoryName)

        ---

        ## Product Specifications

        ### Material
        - **Primary Material:** \(project.material.rawValue)
        \(techPackMaterialDetail(project: project))
        - **Lining:** \(liningLine)

        ### Dimensions
        - **Overall:** \(dimLine)
        - **Print Area:** \(printLine)\(printPx)
        - **Seam Allowance:** \(seamLine)

        ### Print Specifications
        - **Print Method:** \(project.printMethod.rawValue)
        - **Artwork Source:** \(analysis.fileFormat) — \(analysis.pixelWidth) × \(analysis.pixelHeight) px (original)
        - **Repeat Tiles Included:** seamless_2x2.png, seamless_3x3.png, sparse_2x2.png
        - **Print-scaled File Included:** artwork_print_scaled.png\(printPx)

        ### Hardware & Trims
        - **Zipper:** \(zipperLine)
        - **Straps/Handles:** \(strapLine)
        - **Label:** Inner label — brand / care instructions (client to provide artwork)
        - **Hangtag:** Optional — client to confirm

        ### Construction
        - **Closure:** Zipper
        - **Seam Finish:** \(seamLine)
        - **Reinforcement:** Bar tacks at strap attachment points

        ### Order Information
        - **Target Quantity:** \(qtyLine)

        ### Factory Confirmation Required
        1. Confirm MOQ and unit price for quantity above
        2. Confirm lead time from sample approval to delivery
        3. Confirm acceptable color variation tolerance (±__%)
        4. Confirm required artwork file format for your RIP software
        5. Confirm pre-production sample will be provided before bulk run

        ---
        *Generated by PrintFactoryKit — \(hasDims && hasPrint ? "Specifications provided by client." : "⚠️ Some fields incomplete — see items marked above.")*
        """
    }

    func approvalChecklist(project: FactoryProject) -> String {
        return """
        # FACTORY APPROVAL CHECKLIST
        **Project:** \(project.projectCode) — \(project.displayName)
        **Factory:** \(project.factoryName.isEmpty ? "Not specified" : project.displayFactoryName)

        ---

        ## Factory Action Items
        Please review and confirm each item before proceeding.

        ### File Review
        - [ ] Open and verify all files in this package
        - [ ] Confirm artwork file is complete and not corrupted
        - [ ] Confirm color palette document received

        ### Technical Confirmation
        - [ ] Confirm print method is achievable: **\(project.printMethod.rawValue)**
        - [ ] Confirm material is available: **\(project.material.rawValue)**
        - [ ] Confirm artwork resolution is sufficient for requested print dimensions
        - [ ] Confirm repeat tile will be provided (or notify if you require it)
        - [ ] Confirm color profile compatibility (ICC / Pantone / CMYK)

        ### Production Requirements
        - [ ] Confirm physical pre-production sample will be produced
        - [ ] Confirm expected color variation tolerance (±__%)
        - [ ] Confirm production timeline and delivery date
        - [ ] Confirm minimum order quantity (MOQ): _______ units
        - [ ] Confirm unit pricing and payment terms

        ### Sign-off
        - [ ] Factory representative reviewed all documents
        - [ ] Factory confirms capability to produce this product
        - [ ] Physical sample approved by client before proceeding

        ---

        **Factory Representative:** _______________________
        **Date:** ___________________
        **Signature:** _______________________

        ---

        > ⚠️ DO NOT proceed to mass production without client sign-off on physical sample.

        ---
        *Generated by PrintFactoryKit.*
        """
    }

    func supplierMessage(project: FactoryProject) -> String {
        let factoryName = project.factoryName.isEmpty ? "[Factory Name]" : project.displayFactoryName
        return """
        ========================================
        SUPPLIER MESSAGE — FACTORY REVIEW PACKAGE
        ========================================
        PROJECT: \(project.projectCode) — \(project.displayName)
        ========================================

        --- ENGLISH ---

        Dear \(factoryName) Team,

        Please find attached our factory review package for the project:
        "\(project.displayName)" — Collection: \(project.displayCollectionName)

        Package contents:
        - Design Brief
        - Color Palette (approximate — Pantone/CMYK confirmation required)
        - Product Tech Pack (draft)
        - Production Notes
        - Factory Approval Checklist
        - AI Factory Readiness Report
        - Original Artwork (raster source — vectorization required)

        IMPORTANT NOTES:
        • The artwork provided is a raster/bitmap source. Vector files will be provided
          after professional vectorization.
        • Seamless repeat tiles are not yet available — please advise on your requirements.
        • All dimensions in the tech pack are placeholders — please confirm specifications.
        • A physical pre-production sample is mandatory before bulk production.

        Please review all documents and complete the Factory Approval Checklist.
        We look forward to your confirmation and sample timeline.

        Best regards,
        [Your Name / Studio Name]

        ========================================

        --- PORTUGUÊS ---

        Prezada Equipe \(factoryName),

        Segue em anexo nosso pacote de revisão fabril para o projeto:
        "\(project.displayName)" — Coleção: \(project.displayCollectionName)

        Conteúdo do pacote:
        - Brief de Design
        - Paleta de Cores (aproximada — confirmação Pantone/CMYK necessária)
        - Tech Pack do Produto (rascunho)
        - Notas de Produção
        - Checklist de Aprovação de Fábrica
        - Relatório de Prontidão Fabril
        - Arte Original (raster — vetorização necessária)

        AVISOS IMPORTANTES:
        • A arte fornecida é em formato raster/bitmap. Arquivos vetoriais serão
          enviados após vetorização profissional.
        • As peças de repetição seamless ainda não estão disponíveis — por favor,
          informe os requisitos da fábrica.
        • Todas as dimensões no tech pack são marcadores temporários — confirmar
          as especificações.
        • Uma amostra física de pré-produção é obrigatória antes da produção em escala.

        Por favor, revise todos os documentos e preencha o Checklist de Aprovação Fabril.
        Aguardamos sua confirmação e prazo para amostra.

        Atenciosamente,
        [Seu Nome / Nome do Estúdio]

        ========================================
        Generated by PrintFactoryKit
        This package is for factory review only — not approved for mass production.
        ========================================
        """
    }
}
