[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FF9F1A"
backgroundColor = "#030303"
secondaryBackgroundColor = "#111111"
textColor = "#E7E3D7"
font = "sans serif"

[browser]
gatherUsageStats = false
